volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/khiidenh/data/mariadb

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/khiidenh/data/wordpress

networks:
  network:
    name: docker-network
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:10.11.11
    env_file: .env
    ports:
      - "3306:3306"
    healthcheck: #super confusing how to do that?
      test: ["CMD", "mariadb-admin", "ping", "--protocol=tcp", "--host=localhost", "-u", "$MYSQL_USER", "--password=$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - network
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:6.9.4 #depends what kind of version we want to build this on!
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/html/wp-login.php"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - network
    volumes:
     - wordpress:/var/www/html

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:1.26.2 #???
    env_file: .env
    depends_on:
      wordpress:
        condition: service_healthy
    restart: always
    networks:
      - network
    ports:
      - "443:443"  
    volumes:
      - wordpress:/var/www/html

  